spring.application.name=backend

# Conexión a tu MySQL local (Usuario root, contraseña en blanco)
spring.datasource.url=jdbc:mysql://localhost:3306/proyectofinaldnd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de Hibernate para crear las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true